Repository stargate/stargate, pull requests merged in 2020-10, with the labels that each got.

#225 Support list, set and map data types in GraphQL
  graphqlapi/pom.xml
  graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/ddl/DdlQueryFetcher.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/DataTypeMapping.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/DmlFetcher.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/GqlMapBuilder.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/InsertMutationFetcher.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/QueryFetcher.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/UpdateMutationFetcher.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/DmlSchemaBuilderTest.java
  testing/src/main/graphql/betterbotz/collections/GetCollectionsNested.graphql
  testing/src/main/graphql/betterbotz/collections/GetCollectionsSimple.graphql
  testing/src/main/graphql/betterbotz/collections/InsertCollectionsNested.graphql
  testing/src/main/graphql/betterbotz/collections/InsertCollectionsSimple.graphql
  testing/src/main/graphql/betterbotz/collections/UpdateCollectionsNested.graphql
  testing/src/main/graphql/betterbotz/collections/UpdateCollectionsSimple.graphql
  testing/src/main/graphql/betterbotz/schema.json
  testing/src/main/resources/betterbotz.cql
  testing/src/test/java/io/stargate/it/http/GraphqlTest.java
Labels: graphql

#241 Upgrade maven bundle plugin to avoid ConcurrentModificationException
  pom.xml
Labels: hacktoberfest-accepted

#249 add document api diagram change
  assets/stargate-modules.png
Labels: documentation

#248 #83 Auth resource tests
  auth-api/pom.xml
  auth-api/src/main/java/io/stargate/auth/api/resources/AuthResource.java
  auth-api/src/test/java/io/stargate/auth/AuthResourceTest.java
  pom.xml
Labels: hacktoberfest-accepted

#294 Upgrade swagger-jersey2-jaxrs
  auth-api/pom.xml
  restapi/pom.xml
  restapi/src/main/java/io/stargate/web/docsapi/resources/DocumentResourceV2.java
  restapi/src/main/java/io/stargate/web/resources/v2/RowsResource.java
Labels: hacktoberfest-accepted

#286 GraphQL: add collection filters
  graphqlapi/src/main/java/io/stargate/graphql/schema/DmlSchemaBuilder.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/FieldFilterInputTypeCache.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/FieldInputTypeCache.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/FieldOutputTypeCache.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/FieldTypeCache.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/fetchers/dml/DmlFetcher.java
  graphqlapi/src/main/java/io/stargate/graphql/schema/types/GqlMapBuilder.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/DmlSchemaBuilderUdtTest.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/DmlSchemaCollectionsTest.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/DmlSchemaUdtTest.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/FieldFilterInputTypeCacheTest.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/FieldTypeCachesTest.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/SampleKeyspaces.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/SchemaAssertions.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/fetchers/dml/DeleteMutationFetcherCollectionsTest.java
  graphqlapi/src/test/java/io/stargate/graphql/schema/fetchers/dml/QueryFetcherCollectionsTest.java
Labels: graphql

#265 Add one Column Resource Unit Tests
  pom.xml
  restapi/pom.xml
  restapi/src/main/java/io/stargate/web/resources/ColumnResource.java
  restapi/src/test/java/io/stargate/web/resources/ColumnResourceTest.java
Labels: hacktoberfest-accepted

#305 Implement Config-Store API based on the K8s config-map API
  config-store-api/pom.xml
  config-store-api/src/main/java/io/stargate/config/store/api/ConfigStore.java
  config-store-api/src/main/java/io/stargate/config/store/api/ConfigWithOverrides.java
  config-store-api/src/main/java/io/stargate/config/store/api/MissingModuleSettingsException.java
  config-store-api/src/test/java/io/stargate/config/store/api/ConfigWithOverridesTest.java
  config-store-yaml/README.md
  config-store-yaml/pom.xml
  config-store-yaml/src/main/java/io/stargate/config/store/api/yaml/ConfigStoreActivator.java
  config-store-yaml/src/main/java/io/stargate/config/store/api/yaml/ConfigStoreYaml.java
  config-store-yaml/src/test/java/io/stargate/config/store/api/yaml/ConfigStoreActivatorYamlTest.java
  config-store-yaml/src/test/java/io/stargate/config/store/api/yaml/ConfigStoreYamlTest.java
  config-store-yaml/src/test/resources/stargate-config.yaml
  pom.xml
Labels: config-store
