Repository stargate/stargate, pull requests merged in 2023-06, with the labels that each got.

#2617 Remove use of errorprone static analyzer plugin (see #2616 for rationale)
  coordinator/graphqlapi/pom.xml
  coordinator/persistence-api/pom.xml
  coordinator/persistence-api/src/main/java/io/stargate/db/query/TypedValue.java
  coordinator/persistence-api/src/main/java/io/stargate/db/query/builder/QueryBuilderImpl.java
  coordinator/pom.xml
Labels: test, dependencies

#2637 Update Maven plugins to latest versions
  coordinator/pom.xml
Labels: stargate-v2

#2639 Fix #2638: update Guava to 32.0.1 to resolve CVE
  coordinator/persistence-dse-6.8/pom.xml
Labels: stargate-v2

#2641 Remove rate limiting
  coordinator/persistence-api/src/main/java/io/stargate/db/DbActivator.java
  coordinator/persistence-api/src/main/java/io/stargate/db/RateLimitingPersistence.java
  coordinator/persistence-api/src/main/java/io/stargate/db/limiter/AsyncRateLimiter.java
  coordinator/persistence-api/src/main/java/io/stargate/db/limiter/RateLimitingDecision.java
  coordinator/persistence-api/src/main/java/io/stargate/db/limiter/RateLimitingManager.java
  coordinator/persistence-api/src/test/java/io/stargate/db/limiter/AsyncRateLimiterTest.java
  coordinator/pom.xml
  coordinator/rate-limiting-global/pom.xml
  coordinator/rate-limiting-global/src/main/java/io/stargate/db/limiter/global/GlobalRateLimitingActivator.java
  coordinator/rate-limiting-global/src/main/java/io/stargate/db/limiter/global/impl/GlobalRateLimitingManager.java
  coordinator/testing/src/main/java/io/stargate/it/limiter/GlobalRateLimitingTest.java
Labels: v2.1
